name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # weekly build every FRI
    - cron: "0 6 * * 5"

jobs:

  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --version && yarn
      - run: yarn run test:coverage
      - run: yarn run dist:dir
